# .golangci.yml
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Essential linters (current + additions)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Code quality
    - gocyclo
    - gocognit
    - funlen
    
    # Style
    - misspell
    - whitespace
    
    # Error handling
    - errorlint
    - wrapcheck
    - errname
    
    # Performance
    - prealloc
    - perfsprint
    
    # Security
    - gosec
    
    # Test-specific
    - testifylint
    - tparallel
    - thelper
    
    # Best practices
    - revive
    - nakedret
    - unconvert
    - unparam
    - wastedassign

  disable-all: false
  enable-all: false

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  testifylint:
    enable-all: true
    bool-compare:
      ignore-custom-types: false
    expected-actual:
      pattern: "^(expected|want|exp|expectedResult|wantResult)"
    formatter:
      check-format-string: true
      require-f-funcs: false
      require-string-msg: true
    go-require:
      ignore-http-handlers: true
    require-error:
      fn-pattern: "^(Errorf?|NoErrorf?)$"
    suite-extra-assert-call:
      mode: "remove"

  staticcheck:
    checks: ["all"]
    go: "1.25"

  funlen:
    lines: 80
    statements: 50

  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 15

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - funlen
        - gocyclo
        - gocognit
    
    - path: ".*_gen\\.go"
      linters:
        - all

  include-test-files: true